### ISSUE TITLE
Web Workers and Canny Pruning

### ISSUE THREAD

**Issue by blakels** [inspirit/jsfeat#28]
Just curious whether you've considered using web workers to offload detection to another process and if so, where do you stand on that :)

Also, are you going to add canny pruning to the viola jones object detection?

**Comment by jywarren** [comment]
For reference, i tried this out... using `webworkify` -- and wasn't able to get it to run faster than a non-workerized version ☹️ 

https://github.com/jywarren/scrollgraph/pull/1

the difference was pretty dramatic. I'd guess it's the memory buffer copying overhead as @inspirit says, since there's not THAT much else going on here.
